##
# .github/workflows/enforcer.yml
#
# Standard workflow that calls the shared policy-enforcer workflow
#
name: 🛡️ Branch Policy Enforcer
on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  enforce:
    uses: ZAG-Interactive/workflows-policy/.github/workflows/policy-enforcer.yml@main
    secrets: inherit
    with:
      target_branch: ${{ github.event.pull_request.base.ref }}
